apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sistema-matricula-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MarcusxDM/sistema-matricula-ifal-django.git
    targetRevision: develop
    path: helm/sistema-matricula
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: develop-latest    # será substituído pelo pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: sistema-matricula-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - AllowEmpty=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
